enum Tipo {
    STRING,INTEGER,CHAR,DOUBLE,BOOLEAN
}

enum TipoAritmetica{
    SUMA,RESTA,MULTIPLICACION,DIVISION,MODULO
}

enum TipoLogica{
    IGUALDAD,DESIGUALDAD
}

enum TipoError{
    ERROR_GENERAL,OPERACION_NO_PERMITIDA,TIPO_INCORRECTO,VARIABLE_NO_DECLARADA,VARIABLE_YA_DECLARADA,ERROR_LOGICO
}